Framework

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -71,6 +71,66 @@ jobs:
       env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
 
+  links:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: '3.10.x'
+        architecture: 'x64'
+    - name: Cache pip
+      uses: actions/cache@v2
+      with:
+        path: ~/.cache/pip
+        # Look to see if there is a cache hit for the corresponding requirements file
+        key: ${{ runner.os }}-pip-${{ hashFiles('./ci/requirements.txt') }}
+        restore-keys: |
+          ${{ runner.os }}-pip-
+          ${{ runner.os }}-
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install -r ./ci/requirements.txt
+    - name: Use Node.js
+      uses: actions/setup-node@v1
+      with:
+        node-version: '12.x'
+    - name: Install dependencies (Node)
+      run: npm install
+    - name: Set up Hugo
+      uses: peaceiris/actions-hugo@v2
+      with:
+        hugo-version: '0.83.1'
+    - name: Start Hugo server
+      run: |
+        # Start Hugo in background:
+        hugo server &
+
+        # Wait for server to start
+        # (or possibly fail to start):
+        while true
+        do
+            # Check if the server is responding on 1313,
+            # which means that the Hugo build finished.
+            if nc -z localhost 1313
+            then
+                exit 0
+            fi
+
+            # Check if the Hugo process is still running.
+            # If not, then the server failed to build.
+            if ! pgrep hugo > /dev/null
+            then
+                exit 1
+            fi
+
+            sleep 1
+        done
+    - name: Run tests
+      run: python ./ci/links.py
+
   docs404:
     runs-on: ubuntu-latest
     steps:
